name: Generate Snake
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: 1shabbirhussain/snk
        id: snake-gif
  
        with:
          github_user_name: 1shabbirhussain
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: 1shabbirhussain/ghaction-github-pages
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}
